travis:
  secure:
    BINSTAR_TOKEN: alnLM3kp18zg74ORg5Oc1N6nPad+hxWKrLaAUF7VtcsB2d6mBBjcBv5xHtfCBHZTOOSmT0xCY4R2ahyWu1lsE3dtPU3/oreWS3tLFGzkvxb++tVaLnWoTUTq1iN4Dqcjc61zQnBIHEKZrrKG4fqkDRSc/L5xr6W4DsnIyjFlFDFYYwT3UhFOXIXHuX7jZBs2d2HPzPwmiEyBGrGMYnElrKGSrZCdC2+UzGgsA8x6PNcBQWyfCKfiEaM17/ceznvUb3W4WZhjDAtV8wB0xkZsNzyrtI0C8R2StQqu8UXyHIkLNJdnDEiS6RFDHpZHUyJtRJpXeJN7u5ZvvWZ1AOldIzQ+nsN2KbNAy69Cj21ToID7GQUw8bmpKYJJH6fkzfMvpAMRc5dv8jEdCGi/8oIDYQwevim1/lfr2BUhKllT5cNpsD3UcVfTM1njDR7yAgPdajjTnj7SDmp3V8P6epM2iwdrJwU2Na+raaJkd3MX4SdCksCnRz+G+4SmZlSVl0qdYx6fUJoNm3KNAyBAiHGNSfUlKsrpb5DHdydPd9+W4xlUWXZs71n4d8ksWKp+BzCoRAtb2Bih3Zwo8y8SA1ukRAdmOOQNCdjjPIAirrqInS5RqKGiJqgF0osEjiW0oAEkMFDFPow2yxWdaDyqQvdlUEx+lgtt9Eyl/HsdfATzUv0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
